# Generated by Django 3.0.7 on 2020-10-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sample_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('contact', models.CharField(default='', max_length=70)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Query', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
